# Generated by Django 3.0.2 on 2020-01-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='diary_open',
            field=models.CharField(choices=[('yes', 'open'), ('no', 'close')], default='yes', max_length=3),
        ),
    ]
