# Generated by Django 3.0.2 on 2020-01-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200114_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='center_exp',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
    ]
