# Generated by Django 3.0.2 on 2020-01-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additional',
            name='child_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
