# Generated by Django 3.0.2 on 2020-01-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20200114_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='child_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
