# Generated by Django 3.0.2 on 2020-01-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20200114_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='sex',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성')], default='male', max_length=10),
        ),
    ]
